version: '3'
services:
  micro-frontends-challenges-app:
    image: micro-frontends-challenges-app:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    network_mode: "host"
